package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Canal generated by hbm2java
 */
public class Canal  implements java.io.Serializable {


     private int canalCodigo;
     private String canalNombre;
     private int canalNumero;
     private String canalTipo;
     private short canalCosto;
     private byte canalPremium;
     private Set plans = new HashSet(0);
     private Set ticketServicios = new HashSet(0);

    public Canal() {
    }

	
    public Canal(int canalCodigo, String canalNombre, int canalNumero, String canalTipo, short canalCosto, byte canalPremium) {
        this.canalCodigo = canalCodigo;
        this.canalNombre = canalNombre;
        this.canalNumero = canalNumero;
        this.canalTipo = canalTipo;
        this.canalCosto = canalCosto;
        this.canalPremium = canalPremium;
    }
    public Canal(int canalCodigo, String canalNombre, int canalNumero, String canalTipo, short canalCosto, byte canalPremium, Set plans, Set ticketServicios) {
       this.canalCodigo = canalCodigo;
       this.canalNombre = canalNombre;
       this.canalNumero = canalNumero;
       this.canalTipo = canalTipo;
       this.canalCosto = canalCosto;
       this.canalPremium = canalPremium;
       this.plans = plans;
       this.ticketServicios = ticketServicios;
    }
   
    public int getCanalCodigo() {
        return this.canalCodigo;
    }
    
    public void setCanalCodigo(int canalCodigo) {
        this.canalCodigo = canalCodigo;
    }
    public String getCanalNombre() {
        return this.canalNombre;
    }
    
    public void setCanalNombre(String canalNombre) {
        this.canalNombre = canalNombre;
    }
    public int getCanalNumero() {
        return this.canalNumero;
    }
    
    public void setCanalNumero(int canalNumero) {
        this.canalNumero = canalNumero;
    }
    public String getCanalTipo() {
        return this.canalTipo;
    }
    
    public void setCanalTipo(String canalTipo) {
        this.canalTipo = canalTipo;
    }
    public short getCanalCosto() {
        return this.canalCosto;
    }
    
    public void setCanalCosto(short canalCosto) {
        this.canalCosto = canalCosto;
    }
    public byte getCanalPremium() {
        return this.canalPremium;
    }
    
    public void setCanalPremium(byte canalPremium) {
        this.canalPremium = canalPremium;
    }
    public Set getPlans() {
        return this.plans;
    }
    
    public void setPlans(Set plans) {
        this.plans = plans;
    }
    public Set getTicketServicios() {
        return this.ticketServicios;
    }
    
    public void setTicketServicios(Set ticketServicios) {
        this.ticketServicios = ticketServicios;
    }




}


