package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Canal generated by hbm2java
 */
public class Canal  implements java.io.Serializable {


     private Integer canalCodigo;
     private String canalNombre;
     private int canalNumero;
     private String canalTipo;
     private short canalCosto;

    public Canal() {
    }

    public Canal(String canalNombre, int canalNumero, String canalTipo, short canalCosto) {
       this.canalNombre = canalNombre;
       this.canalNumero = canalNumero;
       this.canalTipo = canalTipo;
       this.canalCosto = canalCosto;
    }
   
    public Integer getCanalCodigo() {
        return this.canalCodigo;
    }
    
    public void setCanalCodigo(Integer canalCodigo) {
        this.canalCodigo = canalCodigo;
    }
    public String getCanalNombre() {
        return this.canalNombre;
    }
    
    public void setCanalNombre(String canalNombre) {
        this.canalNombre = canalNombre;
    }
    public int getCanalNumero() {
        return this.canalNumero;
    }
    
    public void setCanalNumero(int canalNumero) {
        this.canalNumero = canalNumero;
    }
    public String getCanalTipo() {
        return this.canalTipo;
    }
    
    public void setCanalTipo(String canalTipo) {
        this.canalTipo = canalTipo;
    }
    public short getCanalCosto() {
        return this.canalCosto;
    }
    
    public void setCanalCosto(short canalCosto) {
        this.canalCosto = canalCosto;
    }




}


