package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private String clienteNombre;
     private String clienteApellido;
     private String clienteTelefono;
     private String clienteCedula;
     private String clienteEmail;
     private String clienteCiudad;
     private String clienteDireccion;

    public Cliente() {
    }

    public Cliente(ClienteId id, String clienteNombre, String clienteApellido, String clienteTelefono, String clienteCedula, String clienteEmail, String clienteCiudad, String clienteDireccion) {
       this.id = id;
       this.clienteNombre = clienteNombre;
       this.clienteApellido = clienteApellido;
       this.clienteTelefono = clienteTelefono;
       this.clienteCedula = clienteCedula;
       this.clienteEmail = clienteEmail;
       this.clienteCiudad = clienteCiudad;
       this.clienteDireccion = clienteDireccion;
    }
   
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }
    public String getClienteNombre() {
        return this.clienteNombre;
    }
    
    public void setClienteNombre(String clienteNombre) {
        this.clienteNombre = clienteNombre;
    }
    public String getClienteApellido() {
        return this.clienteApellido;
    }
    
    public void setClienteApellido(String clienteApellido) {
        this.clienteApellido = clienteApellido;
    }
    public String getClienteTelefono() {
        return this.clienteTelefono;
    }
    
    public void setClienteTelefono(String clienteTelefono) {
        this.clienteTelefono = clienteTelefono;
    }
    public String getClienteCedula() {
        return this.clienteCedula;
    }
    
    public void setClienteCedula(String clienteCedula) {
        this.clienteCedula = clienteCedula;
    }
    public String getClienteEmail() {
        return this.clienteEmail;
    }
    
    public void setClienteEmail(String clienteEmail) {
        this.clienteEmail = clienteEmail;
    }
    public String getClienteCiudad() {
        return this.clienteCiudad;
    }
    
    public void setClienteCiudad(String clienteCiudad) {
        this.clienteCiudad = clienteCiudad;
    }
    public String getClienteDireccion() {
        return this.clienteDireccion;
    }
    
    public void setClienteDireccion(String clienteDireccion) {
        this.clienteDireccion = clienteDireccion;
    }




}


