package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * ClienteId generated by hbm2java
 */
public class ClienteId  implements java.io.Serializable {


     private int usuarioCodigo;
     private int clienteCodigo;

    public ClienteId() {
    }

    public ClienteId(int usuarioCodigo, int clienteCodigo) {
       this.usuarioCodigo = usuarioCodigo;
       this.clienteCodigo = clienteCodigo;
    }
   
    public int getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(int usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public int getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(int clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return (this.getUsuarioCodigo()==castOther.getUsuarioCodigo())
 && (this.getClienteCodigo()==castOther.getClienteCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioCodigo();
         result = 37 * result + this.getClienteCodigo();
         return result;
   }   


}


