package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer contratoCodigo;
     private int usuarioCodigo;
     private int clienteCodigo;
     private Date contratoFecha;
     private byte contratoEstado;

    public Contrato() {
    }

    public Contrato(int usuarioCodigo, int clienteCodigo, Date contratoFecha, byte contratoEstado) {
       this.usuarioCodigo = usuarioCodigo;
       this.clienteCodigo = clienteCodigo;
       this.contratoFecha = contratoFecha;
       this.contratoEstado = contratoEstado;
    }
   
    public Integer getContratoCodigo() {
        return this.contratoCodigo;
    }
    
    public void setContratoCodigo(Integer contratoCodigo) {
        this.contratoCodigo = contratoCodigo;
    }
    public int getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(int usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public int getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(int clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }
    public Date getContratoFecha() {
        return this.contratoFecha;
    }
    
    public void setContratoFecha(Date contratoFecha) {
        this.contratoFecha = contratoFecha;
    }
    public byte getContratoEstado() {
        return this.contratoEstado;
    }
    
    public void setContratoEstado(byte contratoEstado) {
        this.contratoEstado = contratoEstado;
    }




}


