package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int contratoCodigo;
     private Cliente cliente;
     private Date contratoFecha;
     private byte contratoEstado;
     private Set facturas = new HashSet(0);
     private Set detalleContratos = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(int contratoCodigo, Cliente cliente, Date contratoFecha, byte contratoEstado) {
        this.contratoCodigo = contratoCodigo;
        this.cliente = cliente;
        this.contratoFecha = contratoFecha;
        this.contratoEstado = contratoEstado;
    }
    public Contrato(int contratoCodigo, Cliente cliente, Date contratoFecha, byte contratoEstado, Set facturas, Set detalleContratos) {
       this.contratoCodigo = contratoCodigo;
       this.cliente = cliente;
       this.contratoFecha = contratoFecha;
       this.contratoEstado = contratoEstado;
       this.facturas = facturas;
       this.detalleContratos = detalleContratos;
    }
   
    public int getContratoCodigo() {
        return this.contratoCodigo;
    }
    
    public void setContratoCodigo(int contratoCodigo) {
        this.contratoCodigo = contratoCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getContratoFecha() {
        return this.contratoFecha;
    }
    
    public void setContratoFecha(Date contratoFecha) {
        this.contratoFecha = contratoFecha;
    }
    public byte getContratoEstado() {
        return this.contratoEstado;
    }
    
    public void setContratoEstado(byte contratoEstado) {
        this.contratoEstado = contratoEstado;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getDetalleContratos() {
        return this.detalleContratos;
    }
    
    public void setDetalleContratos(Set detalleContratos) {
        this.detalleContratos = detalleContratos;
    }




}


