package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * DetalleContrato generated by hbm2java
 */
public class DetalleContrato  implements java.io.Serializable {


     private Integer detalleContratoCodigo;
     private int contratoCodigo;
     private int planCodigo;

    public DetalleContrato() {
    }

    public DetalleContrato(int contratoCodigo, int planCodigo) {
       this.contratoCodigo = contratoCodigo;
       this.planCodigo = planCodigo;
    }
   
    public Integer getDetalleContratoCodigo() {
        return this.detalleContratoCodigo;
    }
    
    public void setDetalleContratoCodigo(Integer detalleContratoCodigo) {
        this.detalleContratoCodigo = detalleContratoCodigo;
    }
    public int getContratoCodigo() {
        return this.contratoCodigo;
    }
    
    public void setContratoCodigo(int contratoCodigo) {
        this.contratoCodigo = contratoCodigo;
    }
    public int getPlanCodigo() {
        return this.planCodigo;
    }
    
    public void setPlanCodigo(int planCodigo) {
        this.planCodigo = planCodigo;
    }




}


