package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * DetalleContratoEquipoId generated by hbm2java
 */
public class DetalleContratoEquipoId  implements java.io.Serializable {


     private int detalleContratoCodigo;
     private int equipoCodigo;

    public DetalleContratoEquipoId() {
    }

    public DetalleContratoEquipoId(int detalleContratoCodigo, int equipoCodigo) {
       this.detalleContratoCodigo = detalleContratoCodigo;
       this.equipoCodigo = equipoCodigo;
    }
   
    public int getDetalleContratoCodigo() {
        return this.detalleContratoCodigo;
    }
    
    public void setDetalleContratoCodigo(int detalleContratoCodigo) {
        this.detalleContratoCodigo = detalleContratoCodigo;
    }
    public int getEquipoCodigo() {
        return this.equipoCodigo;
    }
    
    public void setEquipoCodigo(int equipoCodigo) {
        this.equipoCodigo = equipoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleContratoEquipoId) ) return false;
		 DetalleContratoEquipoId castOther = ( DetalleContratoEquipoId ) other; 
         
		 return (this.getDetalleContratoCodigo()==castOther.getDetalleContratoCodigo())
 && (this.getEquipoCodigo()==castOther.getEquipoCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDetalleContratoCodigo();
         result = 37 * result + this.getEquipoCodigo();
         return result;
   }   


}


