package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * DetalleContratoEquipo generated by hbm2java
 */
public class DetalleContratoEquipo  implements java.io.Serializable {


     private DetalleContratoEquipoId id;

    public DetalleContratoEquipo() {
    }

    public DetalleContratoEquipo(DetalleContratoEquipoId id) {
       this.id = id;
    }
   
    public DetalleContratoEquipoId getId() {
        return this.id;
    }
    
    public void setId(DetalleContratoEquipoId id) {
        this.id = id;
    }




}


