package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1



/**
 * DetalleContrato generated by hbm2java
 */
public class DetalleContrato  implements java.io.Serializable {


     private int detalleContratoCodigo;
     private Contrato contrato;
     private Plan plan;

    public DetalleContrato() {
    }

    public DetalleContrato(int detalleContratoCodigo, Contrato contrato, Plan plan) {
       this.detalleContratoCodigo = detalleContratoCodigo;
       this.contrato = contrato;
       this.plan = plan;
    }
   
    public int getDetalleContratoCodigo() {
        return this.detalleContratoCodigo;
    }
    
    public void setDetalleContratoCodigo(int detalleContratoCodigo) {
        this.detalleContratoCodigo = detalleContratoCodigo;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Plan getPlan() {
        return this.plan;
    }
    
    public void setPlan(Plan plan) {
        this.plan = plan;
    }




}


