package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private EmpleadoId id;
     private int rolEmpleadoCodigo;
     private String empleadoNombre;
     private String empleadoApellido;

    public Empleado() {
    }

    public Empleado(EmpleadoId id, int rolEmpleadoCodigo, String empleadoNombre, String empleadoApellido) {
       this.id = id;
       this.rolEmpleadoCodigo = rolEmpleadoCodigo;
       this.empleadoNombre = empleadoNombre;
       this.empleadoApellido = empleadoApellido;
    }
   
    public EmpleadoId getId() {
        return this.id;
    }
    
    public void setId(EmpleadoId id) {
        this.id = id;
    }
    public int getRolEmpleadoCodigo() {
        return this.rolEmpleadoCodigo;
    }
    
    public void setRolEmpleadoCodigo(int rolEmpleadoCodigo) {
        this.rolEmpleadoCodigo = rolEmpleadoCodigo;
    }
    public String getEmpleadoNombre() {
        return this.empleadoNombre;
    }
    
    public void setEmpleadoNombre(String empleadoNombre) {
        this.empleadoNombre = empleadoNombre;
    }
    public String getEmpleadoApellido() {
        return this.empleadoApellido;
    }
    
    public void setEmpleadoApellido(String empleadoApellido) {
        this.empleadoApellido = empleadoApellido;
    }




}


