package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoCodigo;
     private RolEmpleado rolEmpleado;
     private Usuario usuario;
     private String empleadoNombre;
     private String empleadoApellido;

    public Empleado() {
    }

    public Empleado(int empleadoCodigo, RolEmpleado rolEmpleado, Usuario usuario, String empleadoNombre, String empleadoApellido) {
       this.empleadoCodigo = empleadoCodigo;
       this.rolEmpleado = rolEmpleado;
       this.usuario = usuario;
       this.empleadoNombre = empleadoNombre;
       this.empleadoApellido = empleadoApellido;
    }
   
    public int getEmpleadoCodigo() {
        return this.empleadoCodigo;
    }
    
    public void setEmpleadoCodigo(int empleadoCodigo) {
        this.empleadoCodigo = empleadoCodigo;
    }
    public RolEmpleado getRolEmpleado() {
        return this.rolEmpleado;
    }
    
    public void setRolEmpleado(RolEmpleado rolEmpleado) {
        this.rolEmpleado = rolEmpleado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEmpleadoNombre() {
        return this.empleadoNombre;
    }
    
    public void setEmpleadoNombre(String empleadoNombre) {
        this.empleadoNombre = empleadoNombre;
    }
    public String getEmpleadoApellido() {
        return this.empleadoApellido;
    }
    
    public void setEmpleadoApellido(String empleadoApellido) {
        this.empleadoApellido = empleadoApellido;
    }




}


