package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * EmpleadoId generated by hbm2java
 */
public class EmpleadoId  implements java.io.Serializable {


     private int usuarioCodigo;
     private int empleadoCodigo;

    public EmpleadoId() {
    }

    public EmpleadoId(int usuarioCodigo, int empleadoCodigo) {
       this.usuarioCodigo = usuarioCodigo;
       this.empleadoCodigo = empleadoCodigo;
    }
   
    public int getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(int usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public int getEmpleadoCodigo() {
        return this.empleadoCodigo;
    }
    
    public void setEmpleadoCodigo(int empleadoCodigo) {
        this.empleadoCodigo = empleadoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoId) ) return false;
		 EmpleadoId castOther = ( EmpleadoId ) other; 
         
		 return (this.getUsuarioCodigo()==castOther.getUsuarioCodigo())
 && (this.getEmpleadoCodigo()==castOther.getEmpleadoCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioCodigo();
         result = 37 * result + this.getEmpleadoCodigo();
         return result;
   }   


}


