package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer equipoCodigo;
     private short equipoCosto;

    public Equipo() {
    }

    public Equipo(short equipoCosto) {
       this.equipoCosto = equipoCosto;
    }
   
    public Integer getEquipoCodigo() {
        return this.equipoCodigo;
    }
    
    public void setEquipoCodigo(Integer equipoCodigo) {
        this.equipoCodigo = equipoCodigo;
    }
    public short getEquipoCosto() {
        return this.equipoCosto;
    }
    
    public void setEquipoCosto(short equipoCosto) {
        this.equipoCosto = equipoCosto;
    }




}


