package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int facturaCodigo;
     private Contrato contrato;
     private Date facturaFecha;
     private Set pagos = new HashSet(0);
     private Set ticketServicios = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int facturaCodigo, Contrato contrato, Date facturaFecha) {
        this.facturaCodigo = facturaCodigo;
        this.contrato = contrato;
        this.facturaFecha = facturaFecha;
    }
    public Factura(int facturaCodigo, Contrato contrato, Date facturaFecha, Set pagos, Set ticketServicios) {
       this.facturaCodigo = facturaCodigo;
       this.contrato = contrato;
       this.facturaFecha = facturaFecha;
       this.pagos = pagos;
       this.ticketServicios = ticketServicios;
    }
   
    public int getFacturaCodigo() {
        return this.facturaCodigo;
    }
    
    public void setFacturaCodigo(int facturaCodigo) {
        this.facturaCodigo = facturaCodigo;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Date getFacturaFecha() {
        return this.facturaFecha;
    }
    
    public void setFacturaFecha(Date facturaFecha) {
        this.facturaFecha = facturaFecha;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getTicketServicios() {
        return this.ticketServicios;
    }
    
    public void setTicketServicios(Set ticketServicios) {
        this.ticketServicios = ticketServicios;
    }




}


