package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private Integer planCodigo;
     private String planNombre;
     private short planTarifa;
     private int planCantidadCanales;
     private int planCanalesSd;
     private int planCanalesHd;
     private int planCanalesAudio;

    public Plan() {
    }

    public Plan(String planNombre, short planTarifa, int planCantidadCanales, int planCanalesSd, int planCanalesHd, int planCanalesAudio) {
       this.planNombre = planNombre;
       this.planTarifa = planTarifa;
       this.planCantidadCanales = planCantidadCanales;
       this.planCanalesSd = planCanalesSd;
       this.planCanalesHd = planCanalesHd;
       this.planCanalesAudio = planCanalesAudio;
    }
   
    public Integer getPlanCodigo() {
        return this.planCodigo;
    }
    
    public void setPlanCodigo(Integer planCodigo) {
        this.planCodigo = planCodigo;
    }
    public String getPlanNombre() {
        return this.planNombre;
    }
    
    public void setPlanNombre(String planNombre) {
        this.planNombre = planNombre;
    }
    public short getPlanTarifa() {
        return this.planTarifa;
    }
    
    public void setPlanTarifa(short planTarifa) {
        this.planTarifa = planTarifa;
    }
    public int getPlanCantidadCanales() {
        return this.planCantidadCanales;
    }
    
    public void setPlanCantidadCanales(int planCantidadCanales) {
        this.planCantidadCanales = planCantidadCanales;
    }
    public int getPlanCanalesSd() {
        return this.planCanalesSd;
    }
    
    public void setPlanCanalesSd(int planCanalesSd) {
        this.planCanalesSd = planCanalesSd;
    }
    public int getPlanCanalesHd() {
        return this.planCanalesHd;
    }
    
    public void setPlanCanalesHd(int planCanalesHd) {
        this.planCanalesHd = planCanalesHd;
    }
    public int getPlanCanalesAudio() {
        return this.planCanalesAudio;
    }
    
    public void setPlanCanalesAudio(int planCanalesAudio) {
        this.planCanalesAudio = planCanalesAudio;
    }




}


