package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * PlanCanal generated by hbm2java
 */
public class PlanCanal  implements java.io.Serializable {


     private PlanCanalId id;

    public PlanCanal() {
    }

    public PlanCanal(PlanCanalId id) {
       this.id = id;
    }
   
    public PlanCanalId getId() {
        return this.id;
    }
    
    public void setId(PlanCanalId id) {
        this.id = id;
    }




}


