package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RolEmpleado generated by hbm2java
 */
public class RolEmpleado  implements java.io.Serializable {


     private int rolEmpleadoCodigo;
     private String rolEmpleadoDescripcion;
     private Set empleados = new HashSet(0);

    public RolEmpleado() {
    }

	
    public RolEmpleado(int rolEmpleadoCodigo, String rolEmpleadoDescripcion) {
        this.rolEmpleadoCodigo = rolEmpleadoCodigo;
        this.rolEmpleadoDescripcion = rolEmpleadoDescripcion;
    }
    public RolEmpleado(int rolEmpleadoCodigo, String rolEmpleadoDescripcion, Set empleados) {
       this.rolEmpleadoCodigo = rolEmpleadoCodigo;
       this.rolEmpleadoDescripcion = rolEmpleadoDescripcion;
       this.empleados = empleados;
    }
   
    public int getRolEmpleadoCodigo() {
        return this.rolEmpleadoCodigo;
    }
    
    public void setRolEmpleadoCodigo(int rolEmpleadoCodigo) {
        this.rolEmpleadoCodigo = rolEmpleadoCodigo;
    }
    public String getRolEmpleadoDescripcion() {
        return this.rolEmpleadoDescripcion;
    }
    
    public void setRolEmpleadoDescripcion(String rolEmpleadoDescripcion) {
        this.rolEmpleadoDescripcion = rolEmpleadoDescripcion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


