package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * RolEmpleado generated by hbm2java
 */
public class RolEmpleado  implements java.io.Serializable {


     private Integer rolEmpleadoCodigo;
     private String rolEmpleadoDescripcion;

    public RolEmpleado() {
    }

    public RolEmpleado(String rolEmpleadoDescripcion) {
       this.rolEmpleadoDescripcion = rolEmpleadoDescripcion;
    }
   
    public Integer getRolEmpleadoCodigo() {
        return this.rolEmpleadoCodigo;
    }
    
    public void setRolEmpleadoCodigo(Integer rolEmpleadoCodigo) {
        this.rolEmpleadoCodigo = rolEmpleadoCodigo;
    }
    public String getRolEmpleadoDescripcion() {
        return this.rolEmpleadoDescripcion;
    }
    
    public void setRolEmpleadoDescripcion(String rolEmpleadoDescripcion) {
        this.rolEmpleadoDescripcion = rolEmpleadoDescripcion;
    }




}


