package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * ServicioAdicional generated by hbm2java
 */
public class ServicioAdicional  implements java.io.Serializable {


     private Integer servicioAdicionalCodigo;
     private String servicioAdicionalDetalle;
     private short servicioAdicionalCosto;

    public ServicioAdicional() {
    }

    public ServicioAdicional(String servicioAdicionalDetalle, short servicioAdicionalCosto) {
       this.servicioAdicionalDetalle = servicioAdicionalDetalle;
       this.servicioAdicionalCosto = servicioAdicionalCosto;
    }
   
    public Integer getServicioAdicionalCodigo() {
        return this.servicioAdicionalCodigo;
    }
    
    public void setServicioAdicionalCodigo(Integer servicioAdicionalCodigo) {
        this.servicioAdicionalCodigo = servicioAdicionalCodigo;
    }
    public String getServicioAdicionalDetalle() {
        return this.servicioAdicionalDetalle;
    }
    
    public void setServicioAdicionalDetalle(String servicioAdicionalDetalle) {
        this.servicioAdicionalDetalle = servicioAdicionalDetalle;
    }
    public short getServicioAdicionalCosto() {
        return this.servicioAdicionalCosto;
    }
    
    public void setServicioAdicionalCosto(short servicioAdicionalCosto) {
        this.servicioAdicionalCosto = servicioAdicionalCosto;
    }




}


