package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TicketServicio generated by hbm2java
 */
public class TicketServicio  implements java.io.Serializable {


     private Integer ticketServicioCodigo;
     private int facturaCodigo;
     private int servicioAdicionalCodigo;
     private Date ticketServicioFecha;

    public TicketServicio() {
    }

    public TicketServicio(int facturaCodigo, int servicioAdicionalCodigo, Date ticketServicioFecha) {
       this.facturaCodigo = facturaCodigo;
       this.servicioAdicionalCodigo = servicioAdicionalCodigo;
       this.ticketServicioFecha = ticketServicioFecha;
    }
   
    public Integer getTicketServicioCodigo() {
        return this.ticketServicioCodigo;
    }
    
    public void setTicketServicioCodigo(Integer ticketServicioCodigo) {
        this.ticketServicioCodigo = ticketServicioCodigo;
    }
    public int getFacturaCodigo() {
        return this.facturaCodigo;
    }
    
    public void setFacturaCodigo(int facturaCodigo) {
        this.facturaCodigo = facturaCodigo;
    }
    public int getServicioAdicionalCodigo() {
        return this.servicioAdicionalCodigo;
    }
    
    public void setServicioAdicionalCodigo(int servicioAdicionalCodigo) {
        this.servicioAdicionalCodigo = servicioAdicionalCodigo;
    }
    public Date getTicketServicioFecha() {
        return this.ticketServicioFecha;
    }
    
    public void setTicketServicioFecha(Date ticketServicioFecha) {
        this.ticketServicioFecha = ticketServicioFecha;
    }




}


