package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TicketServicio generated by hbm2java
 */
public class TicketServicio  implements java.io.Serializable {


     private int ticketServicioCodigo;
     private Factura factura;
     private ServicioAdicional servicioAdicional;
     private Date ticketServicioFecha;
     private Set canals = new HashSet(0);

    public TicketServicio() {
    }

	
    public TicketServicio(int ticketServicioCodigo, Factura factura, ServicioAdicional servicioAdicional, Date ticketServicioFecha) {
        this.ticketServicioCodigo = ticketServicioCodigo;
        this.factura = factura;
        this.servicioAdicional = servicioAdicional;
        this.ticketServicioFecha = ticketServicioFecha;
    }
    public TicketServicio(int ticketServicioCodigo, Factura factura, ServicioAdicional servicioAdicional, Date ticketServicioFecha, Set canals) {
       this.ticketServicioCodigo = ticketServicioCodigo;
       this.factura = factura;
       this.servicioAdicional = servicioAdicional;
       this.ticketServicioFecha = ticketServicioFecha;
       this.canals = canals;
    }
   
    public int getTicketServicioCodigo() {
        return this.ticketServicioCodigo;
    }
    
    public void setTicketServicioCodigo(int ticketServicioCodigo) {
        this.ticketServicioCodigo = ticketServicioCodigo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public ServicioAdicional getServicioAdicional() {
        return this.servicioAdicional;
    }
    
    public void setServicioAdicional(ServicioAdicional servicioAdicional) {
        this.servicioAdicional = servicioAdicional;
    }
    public Date getTicketServicioFecha() {
        return this.ticketServicioFecha;
    }
    
    public void setTicketServicioFecha(Date ticketServicioFecha) {
        this.ticketServicioFecha = ticketServicioFecha;
    }
    public Set getCanals() {
        return this.canals;
    }
    
    public void setCanals(Set canals) {
        this.canals = canals;
    }




}


