package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * TicketServicioCanal generated by hbm2java
 */
public class TicketServicioCanal  implements java.io.Serializable {


     private TicketServicioCanalId id;

    public TicketServicioCanal() {
    }

    public TicketServicioCanal(TicketServicioCanalId id) {
       this.id = id;
    }
   
    public TicketServicioCanalId getId() {
        return this.id;
    }
    
    public void setId(TicketServicioCanalId id) {
        this.id = id;
    }




}


