package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * TicketServicioCanalId generated by hbm2java
 */
public class TicketServicioCanalId  implements java.io.Serializable {


     private int ticketServicioCodigo;
     private int canalCodigo;

    public TicketServicioCanalId() {
    }

    public TicketServicioCanalId(int ticketServicioCodigo, int canalCodigo) {
       this.ticketServicioCodigo = ticketServicioCodigo;
       this.canalCodigo = canalCodigo;
    }
   
    public int getTicketServicioCodigo() {
        return this.ticketServicioCodigo;
    }
    
    public void setTicketServicioCodigo(int ticketServicioCodigo) {
        this.ticketServicioCodigo = ticketServicioCodigo;
    }
    public int getCanalCodigo() {
        return this.canalCodigo;
    }
    
    public void setCanalCodigo(int canalCodigo) {
        this.canalCodigo = canalCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TicketServicioCanalId) ) return false;
		 TicketServicioCanalId castOther = ( TicketServicioCanalId ) other; 
         
		 return (this.getTicketServicioCodigo()==castOther.getTicketServicioCodigo())
 && (this.getCanalCodigo()==castOther.getCanalCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTicketServicioCodigo();
         result = 37 * result + this.getCanalCodigo();
         return result;
   }   


}


