package server.tv.map;
// Generated Dec 5, 2016 10:36:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int usuarioCodigo;
     private String usuarioNombre;
     private String usuarioClave;
     private Set empleados = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int usuarioCodigo, String usuarioNombre, String usuarioClave) {
        this.usuarioCodigo = usuarioCodigo;
        this.usuarioNombre = usuarioNombre;
        this.usuarioClave = usuarioClave;
    }
    public Usuario(int usuarioCodigo, String usuarioNombre, String usuarioClave, Set empleados) {
       this.usuarioCodigo = usuarioCodigo;
       this.usuarioNombre = usuarioNombre;
       this.usuarioClave = usuarioClave;
       this.empleados = empleados;
    }
   
    public int getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(int usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioClave() {
        return this.usuarioClave;
    }
    
    public void setUsuarioClave(String usuarioClave) {
        this.usuarioClave = usuarioClave;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


