package server.tv.map;
// Generated 03-dic-2016 13:57:40 by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioCodigo;
     private String usuarioNombre;
     private String usuarioClave;

    public Usuario() {
    }

    public Usuario(String usuarioNombre, String usuarioClave) {
       this.usuarioNombre = usuarioNombre;
       this.usuarioClave = usuarioClave;
    }
   
    public Integer getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(Integer usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioClave() {
        return this.usuarioClave;
    }
    
    public void setUsuarioClave(String usuarioClave) {
        this.usuarioClave = usuarioClave;
    }




}


